<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SiteSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            [
                'key' => 'site_name',
                'value' => 'Borsa Gazetesi',
                'type' => 'text',
                'description' => 'Site adı',
                'group' => 'general',
                'label' => 'Site Adı',
                'sort_order' => 1,
                'is_required' => true,
                'options' => null,
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'site_description',
                'value' => 'Güncel borsa haberleri ve analizleri',
                'type' => 'text',
                'description' => 'Site açıklaması',
                'group' => 'general',
                'label' => 'Site Açıklaması',
                'sort_order' => 2,
                'is_required' => false,
                'options' => null,
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'site_logo',
                'value' => '/images/logo.png',
                'type' => 'image',
                'description' => 'Site logosu',
                'group' => 'general',
                'label' => 'Site Logosu',
                'sort_order' => 3,
                'is_required' => false,
                'options' => null,
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'contact_email',
                'value' => 'info@borsagazetesi.com',
                'type' => 'text',
                'description' => 'İletişim e-posta adresi',
                'group' => 'contact',
                'label' => 'İletişim E-posta',
                'sort_order' => 1,
                'is_required' => true,
                'options' => null,
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'contact_phone',
                'value' => '+90 212 555 0123',
                'type' => 'text',
                'description' => 'İletişim telefon numarası',
                'group' => 'contact',
                'label' => 'İletişim Telefon',
                'sort_order' => 2,
                'is_required' => false,
                'options' => null,
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // SEO Ayarları
            [
                'key' => 'meta_title',
                'value' => 'Borsa Gazetesi - Güncel Borsa Haberleri',
                'type' => 'text',
                'description' => 'Ana sayfa meta title',
                'group' => 'seo',
                'label' => 'Meta Title',
                'sort_order' => 1,
                'is_required' => true,
                'options' => null,
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'meta_description',
                'value' => 'Güncel borsa haberleri, analizler ve yorumlar. Borsa Gazetesi ile finans dünyasını takip edin.',
                'type' => 'textarea',
                'description' => 'Ana sayfa meta description',
                'group' => 'seo',
                'label' => 'Meta Description',
                'sort_order' => 2,
                'is_required' => true,
                'options' => null,
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'meta_keywords',
                'value' => 'borsa, haber, analiz, finans, ekonomi, hisse senedi',
                'type' => 'text',
                'description' => 'Ana sayfa meta keywords',
                'group' => 'seo',
                'label' => 'Meta Keywords',
                'sort_order' => 3,
                'is_required' => false,
                'options' => null,
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'google_analytics',
                'value' => '',
                'type' => 'text',
                'description' => 'Google Analytics tracking kodu',
                'group' => 'seo',
                'label' => 'Google Analytics ID',
                'sort_order' => 4,
                'is_required' => false,
                'options' => null,
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Sosyal Medya Ayarları
            [
                'key' => 'facebook_url',
                'value' => 'https://facebook.com/borsagazetesi',
                'type' => 'text',
                'description' => 'Facebook sayfa URL',
                'group' => 'social',
                'label' => 'Facebook URL',
                'sort_order' => 1,
                'is_required' => false,
                'options' => null,
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'twitter_url',
                'value' => 'https://twitter.com/borsagazetesi',
                'type' => 'text',
                'description' => 'Twitter profil URL',
                'group' => 'social',
                'label' => 'Twitter URL',
                'sort_order' => 2,
                'is_required' => false,
                'options' => null,
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'instagram_url',
                'value' => 'https://instagram.com/borsagazetesi',
                'type' => 'text',
                'description' => 'Instagram profil URL',
                'group' => 'social',
                'label' => 'Instagram URL',
                'sort_order' => 3,
                'is_required' => false,
                'options' => null,
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'linkedin_url',
                'value' => 'https://linkedin.com/company/borsagazetesi',
                'type' => 'text',
                'description' => 'LinkedIn şirket sayfası URL',
                'group' => 'social',
                'label' => 'LinkedIn URL',
                'sort_order' => 4,
                'is_required' => false,
                'options' => null,
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'youtube_url',
                'value' => 'https://youtube.com/borsagazetesi',
                'type' => 'text',
                'description' => 'YouTube kanal URL',
                'group' => 'social',
                'label' => 'YouTube URL',
                'sort_order' => 5,
                'is_required' => false,
                'options' => null,
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // E-posta Ayarları
            [
                'key' => 'smtp_host',
                'value' => 'smtp.gmail.com',
                'type' => 'text',
                'description' => 'SMTP sunucu adresi',
                'group' => 'email',
                'label' => 'SMTP Host',
                'sort_order' => 1,
                'is_required' => true,
                'options' => null,
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'smtp_port',
                'value' => '587',
                'type' => 'text',
                'description' => 'SMTP port numarası',
                'group' => 'email',
                'label' => 'SMTP Port',
                'sort_order' => 2,
                'is_required' => true,
                'options' => null,
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'smtp_username',
                'value' => 'noreply@borsagazetesi.com',
                'type' => 'text',
                'description' => 'SMTP kullanıcı adı',
                'group' => 'email',
                'label' => 'SMTP Kullanıcı Adı',
                'sort_order' => 3,
                'is_required' => true,
                'options' => null,
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'smtp_password',
                'value' => '',
                'type' => 'text',
                'description' => 'SMTP şifre',
                'group' => 'email',
                'label' => 'SMTP Şifre',
                'sort_order' => 4,
                'is_required' => true,
                'options' => null,
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'smtp_encryption',
                'value' => 'tls',
                'type' => 'select',
                'description' => 'SMTP şifreleme türü',
                'group' => 'email',
                'label' => 'SMTP Şifreleme',
                'sort_order' => 5,
                'is_required' => true,
                'options' => json_encode([
                    ['value' => 'tls', 'label' => 'TLS'],
                    ['value' => 'ssl', 'label' => 'SSL'],
                    ['value' => '', 'label' => 'Yok'],
                ]),
                'is_public' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Menü Yönetimi
            [
                'key' => 'main_menu_style',
                'value' => 'horizontal',
                'type' => 'select',
                'description' => 'Ana menü görünüm stili',
                'group' => 'menu',
                'label' => 'Ana Menü Stili',
                'sort_order' => 1,
                'is_required' => true,
                'options' => json_encode([
                    ['value' => 'horizontal', 'label' => 'Yatay'],
                    ['value' => 'vertical', 'label' => 'Dikey'],
                    ['value' => 'dropdown', 'label' => 'Açılır Menü'],
                ]),
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'menu_animation',
                'value' => 'fade',
                'type' => 'select',
                'description' => 'Menü animasyon türü',
                'group' => 'menu',
                'label' => 'Menü Animasyonu',
                'sort_order' => 2,
                'is_required' => true,
                'options' => json_encode([
                    ['value' => 'fade', 'label' => 'Fade'],
                    ['value' => 'slide', 'label' => 'Slide'],
                    ['value' => 'none', 'label' => 'Yok'],
                ]),
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'key' => 'show_breadcrumb',
                'value' => true,
                'type' => 'boolean',
                'description' => 'Breadcrumb gösterilsin mi?',
                'group' => 'menu',
                'label' => 'Breadcrumb Göster',
                'sort_order' => 3,
                'is_required' => false,
                'options' => null,
                'is_public' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($settings as $setting) {
            $setting['is_active'] = true; // is_active kolonu ekle
            DB::table('site_settings')->insert($setting);
        }
    }
}
